"""Generates Markdown and JSON reports from agent execution results."""

from __future__ import annotations

import json
import os
import time
from typing import Any, Dict, List


class ReportBuilder:
    """Build Markdown and JSON reports from agent execution data."""

    def __init__(self, output_dir: str = "output"):
        self.output_dir = output_dir
        os.makedirs(output_dir, exist_ok=True)

    def build_markdown(self, data: Dict[str, Any]) -> str:
        """Generate a full Markdown report string."""
        lines: List[str] = []

        # Header
        lines.append("# 🤖 Agentic AI — Execution Report")
        lines.append("")
        lines.append(f"**Generated:** {data['timing']['end']}")
        lines.append(f"**Duration:** {data['timing']['duration_seconds']} seconds")
        lines.append("")

        # Goal
        lines.append("---")
        lines.append("## 🎯 Goal")
        lines.append("")
        lines.append(f"> {data['goal']}")
        lines.append("")

        # Plan
        lines.append("---")
        lines.append("## 📋 Plan")
        lines.append("")
        lines.append("| Step | Description | Tool | Fallback | Status |")
        lines.append("|------|-------------|------|----------|--------|")
        for step in data["plan"]:
            status_icon = self._status_icon(step["status"])
            fallback = step.get("fallback_tool") or "—"
            lines.append(
                f"| {step['step_id']} "
                f"| {step['description'][:60]} "
                f"| `{step['tool']}` "
                f"| `{fallback}` "
                f"| {status_icon} {step['status']} |"
            )
        lines.append("")

        # Execution Trace
        lines.append("---")
        lines.append("## ⚙️ Execution Trace")
        lines.append("")
        for entry in data["execution_trace"]:
            icon = self._status_icon(entry["status"])
            lines.append(
                f"- **Step {entry['step_id']}** — `{entry['tool']}` "
                f"→ {icon} {entry['status']} "
                f"({entry['duration_ms']:.1f} ms)"
            )
            if entry.get("error"):
                lines.append(f"  - ⚠️ *{entry['error']}*")
        lines.append("")

        # Error Recovery
        recovery = data.get("recovery_events", [])
        if recovery:
            lines.append("---")
            lines.append("## 🔄 Error Recovery Events")
            lines.append("")
            for evt in recovery:
                lines.append(
                    f"- **Step {evt['step_id']}** — "
                    f"Action: **{evt['action']}** (attempt {evt['attempt']})"
                )
                lines.append(f"  - Reason: *{evt['reason']}*")
                lines.append(f"  - Outcome: {evt['outcome']}")
            lines.append("")

        # Step Results
        lines.append("---")
        lines.append("## 📊 Step Results")
        lines.append("")
        for sr in data.get("step_results", []):
            status_icon = self._status_icon(sr["status"])
            lines.append(f"### Step {sr['step_id']}: {sr['description'][:80]}")
            lines.append(f"- **Tool:** `{sr['tool']}`")
            lines.append(f"- **Status:** {status_icon} {sr['status']}")
            if sr["retries"]:
                lines.append(f"- **Retries:** {sr['retries']}")
            lines.append(f"- **Result preview:**")
            lines.append(f"  ```")
            lines.append(f"  {sr['result_preview']}")
            lines.append(f"  ```")
            lines.append("")

        # Statistics
        lines.append("---")
        lines.append("## 📈 Statistics")
        lines.append("")
        stats = data.get("statistics", {})
        lines.append(f"| Metric | Value |")
        lines.append(f"|--------|-------|")
        lines.append(f"| Total Steps | {stats.get('total_steps', 'N/A')} |")
        lines.append(f"| Succeeded | {stats.get('succeeded', 'N/A')} |")
        lines.append(f"| Failed | {stats.get('failed', 'N/A')} |")
        lines.append(f"| Total Retries | {stats.get('total_retries', 'N/A')} |")
        lines.append(f"| Success Rate | {stats.get('success_rate', 'N/A')} |")
        lines.append("")

        # Tools
        lines.append("---")
        lines.append("## 🔧 Tools Available")
        lines.append("")
        for t in data.get("tools_available", []):
            lines.append(f"- `{t}`")
        lines.append("")

        lines.append("---")
        lines.append("*Report generated by Agentic AI Research Agent v1.0*")

        return "\n".join(lines)

    def build_json(self, data: Dict[str, Any]) -> str:
        """Generate a pretty-printed JSON report string."""
        return json.dumps(data, indent=2, default=str)

    def save(self, data: Dict[str, Any], base_name: str = "report") -> Dict[str, str]:
        """Save both Markdown and JSON reports to the output directory."""
        timestamp = time.strftime("%Y%m%d_%H%M%S")
        md_name = f"{base_name}_{timestamp}.md"
        json_name = f"{base_name}_{timestamp}.json"

        md_path = os.path.join(self.output_dir, md_name)
        json_path = os.path.join(self.output_dir, json_name)

        md_content = self.build_markdown(data)
        json_content = self.build_json(data)

        with open(md_path, "w", encoding="utf-8") as f:
            f.write(md_content)

        with open(json_path, "w", encoding="utf-8") as f:
            f.write(json_content)

        return {"markdown": md_path, "json": json_path}

    # ---- helpers ---------------------------------------------------------------

    @staticmethod
    def _status_icon(status: str) -> str:
        return {
            "success": "✅",
            "failed": "❌",
            "timeout": "⏱️",
            "partial": "⚠️",
            "pending": "⏳",
            "running": "🔄",
            "retried": "🔁",
            "skipped": "⏭️",
        }.get(status, "❓")
